M48
; DRILL file {KiCad 9.0.7} date 2026-01-28T16:33:11-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-28T16:33:11-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0571
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.728Y-4.574
T2
X3.1826Y-3.1826
X3.1826Y-4.6914
X4.6914Y-3.1826
X4.6914Y-4.6914
M30
